<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SNCOIC Training Report</name>
   <tag></tag>
   <elementGuidId>de9b001a-0d56-4faa-a2ec-8bf50cd02e1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='0.3799615159437578']/div/div/div/div[2]/div/div[2]/div[2]/div/div/div[2]/div[38]/div/div/div[3]/div/div/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appian-feed-entry-author</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-selectable</name>
      <type>Main</type>
      <value>unselectable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/suite/tempo/reports/view/dsCAdQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SNCOIC Training Report</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0.3799615159437578&quot;)/div[@class=&quot;appian-gwt GBBMY-ICK appian-reports&quot;]/div[@class=&quot;main_content&quot;]/div[@class=&quot;GBBMY-IEK&quot;]/div[@class=&quot;content_main&quot;]/div[@class=&quot;GBBMY-ILK&quot;]/div[@class=&quot;list_content&quot;]/div[2]/div[1]/div[@class=&quot;appian-feed-component GBBMY-ID2B&quot;]/div[@class=&quot;GBBMY-IB2B&quot;]/div[@class=&quot;appian-feed-entry GBBMY-ILQC&quot;]/div[1]/div[@class=&quot;GBBMY-IGCC&quot;]/div[@class=&quot;GBBMY-IJQC&quot;]/div[@class=&quot;GBBMY-IKTC&quot;]/div[@class=&quot;GBBMY-ILTC&quot;]/span[@class=&quot;appian-feed-entry-target&quot;]/a[@class=&quot;appian-feed-entry-author&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0.3799615159437578']/div/div/div/div[2]/div/div[2]/div[2]/div/div/div[2]/div[38]/div/div/div[3]/div/div/span/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SNCOIC Training Report')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report to display scrubbed prospects'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scrubbed Prospect Report'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Displays training provided by selected SNCOIC'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sprint 32 Demo Videos'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SNCOIC Training Report']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/suite/tempo/reports/view/dsCAdQ')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[38]/div/div/div[3]/div/div/span/a</value>
   </webElementXpaths>
</WebElementEntity>
