<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Billets</name>
   <tag></tag>
   <elementGuidId>b801c431-e353-4356-9b1f-468260f3145c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Billets' or . = 'Billets')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sitesBody']/div/div/div[3]/div/div/div/div/div/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/p/strong/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AccentText---color_accent AccentText---inStrongText</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Billets</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sitesBody&quot;)/div[1]/div[@class=&quot;ContentLayout---content_layout ContentLayout---padding_more&quot;]/div[@class=&quot;SectionLayout2---sectionLayout&quot;]/div[@class=&quot;rah-static rah-static--height-auto&quot;]/div[1]/div[@class=&quot;SectionLayout2---section_contents SectionLayout2---margin_below_standard&quot;]/div[@class=&quot;ColumnArrayLayout---column_layout ColumnArrayLayout---full ColumnArrayLayout---fixed appian-context-last-in-list&quot;]/div[@class=&quot;ColumnLayout---column ColumnLayout---align_start ColumnLayout---top appian-context-last-in-list&quot;]/div[@class=&quot;MultiColumnLayout---column_layout MultiColumnLayout---full MultiColumnLayout---fixed&quot;]/div[@class=&quot;ColumnLayout---column ColumnLayout---align_start ColumnLayout---top&quot;]/div[@class=&quot;CardLayout---card_item CardLayout---margin_below_standard CardLayout---border_visible CardLayout---height_auto CardLayout---width_fit CardLayout---linkedCard&quot;]/div[@class=&quot;ContentLayout---content_layout ContentLayout---padding_less&quot;]/div[@class=&quot;FieldLayout---field_layout appian-context-last-in-list&quot;]/div[@class=&quot;FieldLayout---input_below&quot;]/div[@class=&quot;SideBySideGroup---side_by_side SideBySideGroup---default_direction SideBySideGroup---middle&quot;]/div[@class=&quot;SideBySideItem---flex_item SideBySideItem---default_direction appian-context-last-in-list&quot;]/div[@class=&quot;ColumnLayout---column ColumnLayout---align_start ColumnLayout---top&quot;]/div[@class=&quot;FieldLayout---field_layout FieldLayout---inSideBySideItem&quot;]/div[@class=&quot;FieldLayout---input_below&quot;]/div[1]/p[@class=&quot;ParagraphText---richtext_paragraph ParagraphText---default_direction ParagraphText---align_start ParagraphText---nowrap elements---global_p&quot;]/strong[@class=&quot;StrongText---richtext_strong&quot;]/span[@class=&quot;AccentText---color_accent AccentText---inStrongText&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sitesBody']/div/div/div[3]/div/div/div/div/div/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/p/strong/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Icon'])[5]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billets'])[1]/following::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career Recruiter Packages'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Icon'])[6]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/p/strong/span</value>
   </webElementXpaths>
</WebElementEntity>
